services:
  discord-bot:
    container_name: reudiger-ruediger-dev
    build:
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-password}@postgres-db:${DATABASE_PORT:-5432}/${DATABASE_NAME:-reudiger-ruediger}
    command: ['npm', 'run', 'dev']

  postgres-db:
    ports:
      - '127.0.0.1:5432:5432'
