services:
  discord-bot:
    container_name: reudiger-ruediger-dev
    build:
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ['npm', 'run', 'dev']
    networks:
      - reudiger-network

  postgres-db:
    container_name: '${DATABASE_NAME:-sample-bot}-postgres'
    ports:
      - '127.0.0.1:${DATABASE_PORT:-5432}:5432'
    networks:
      - reudiger-network
