services:
  discord-bot:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres-db
    networks:
      - reudiger-network

  postgres-db:
    container_name: '${DATABASE_NAME:-sample-bot}-postgres'
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: '${DATABASE_USER:-postgres}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD:-password}'
      POSTGRES_DB: '${DATABASE_NAME:-sample-bot}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - reudiger-network

volumes:
  pgdata:
    name: '${DATABASE_NAME:-sample-bot}-pgdata'

networks:
  reudiger-network:
    driver: bridge
