services:
  discord-bot:
    container_name: reudiger-ruediger-prod
    build:
      target: production
    environment:
      NODE_ENV: production
    develop: null
    volumes: []
    command: ['node', 'dist/index.js']
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - reudiger-network

  migrate:
    container_name: reudiger-ruediger-migrate
    build:
      context: .
      target: migrate
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: ['npm', 'run', 'db:migrate']
    depends_on:
      - postgres-db
    restart: 'no'
    networks:
      - reudiger-network

  postgres-db:
    container_name: '${DATABASE_NAME}-postgres-prod'
    ports: []
    restart: always
    networks:
      - reudiger-network
